---
- name: Copy systemd service
  become: yes
  template:
    src: "odoo.service.j2"
    dest: "/etc/systemd/system/odoo.service"
    mode: 02775
    owner: "{{ odoo_role_odoo_user }}"
    group: "{{ odoo_role_odoo_group }}"

- name: Enable service
  become: yes
  systemd:
    name: "{{ odoo_daemon }}"
    enabled: yes
    state: started
    daemon_reload: yes
  notify: restart odoo

- name: Copy systemd cron service
  become: yes
  template:
    src: "odoo-cron.service.j2"
    dest: "/etc/systemd/system/odoo-cron.service"
    mode: 02775
    owner: "{{ odoo_role_odoo_user }}"
    group: "{{ odoo_role_odoo_group }}"

- name: Enable cron service
  become: yes
  systemd:
    name: "{{ odoo_cron_daemon }}"
    enabled: yes
    state: started
    daemon_reload: yes
  notify: restart odoo
